import { checkboxRules } from '../channels/routing';
import { decodeUtf8, fromBase64 } from '../crypto/encoding';
import { downloadBrowserFile, formatBytes, uploadBrowserFile } from '../files/transfer';
import { FILE_MANIFEST_CONTENT_TYPE, type RouteSelection } from '../shared/types';

const root=document.querySelector<HTMLElement>('#app')!;
const connection=document.querySelector<HTMLElement>('#connection')!;
let state:any;

void load();
async function load():Promise<void>{try{state=await command('get-state');if(!state.configured){root.innerHTML='<section class="section"><h1>Pairing required</h1><p>Open the ClipMesh toolbar popup while viewing your server onboarding page.</p></section>';return;}render();}catch(error){root.innerHTML=`<p class="form-error">${escapeText(message(error))}</p>`;}}

function render():void{
  connection.textContent=state.connection;connection.className=`status ${state.connection==='connected'?'connected':''}`;const rules=checkboxRules(state.routes as RouteSelection[],(id)=>state.channels.find((channel:any)=>channel.id===id)?.name??id);const currentText=state.current?.type==='text/plain'?decodeUtf8(fromBase64(state.current.bytes)):'';const hasSend=state.routes.some((route:any)=>route.sendEnabled);
  root.innerHTML=`<nav class="sidebar"><button class="active" data-scroll="device">Device</button><button data-scroll="server">Server</button><button data-scroll="channels">Channels</button><button data-scroll="clipboard">Clipboard</button><button data-scroll="history">History</button><button data-scroll="security">Security</button></nav><div class="page"><h1>Your encrypted mesh</h1><p class="lede">${escapeText(state.server.url)} · ${escapeText(state.mode)} mode</p>${state.clipboardError?`<p class="notice">${escapeText(state.clipboardError)}. Grant clipboard access in Chrome and use Reload from clipboard.</p>`:''}${state.operationError?`<p class="notice">Latest operation warning: ${escapeText(state.operationError)}</p>`:''}${state.pending?`<p class="notice">Only the newest offline item is retained. ${state.pending.contentType==='text/plain'?'Text':'PNG image'} captured ${new Date(state.pending.capturedAt).toLocaleString()} is pending for ${state.pending.targetChannelIds.length} channel(s).</p>`:''}
  <section class="section" id="device"><h2>Device</h2><div class="split"><label>Device name<input id="device-name" maxlength="80" value="${escapeText(state.server.deviceName)}"></label><label>Device ID<input readonly value="${state.server.deviceId}"></label><label>Browser and OS<input readonly value="Chrome · ${escapeText(state.client.os)}"></label><label>Last server connection<input readonly value="${state.client.lastConnection?new Date(state.client.lastConnection).toLocaleString():'Never'}"></label></div><div class="actions" style="margin-top:12px"><button class="primary" id="rename">Save name</button><button id="reconnect">Reconnect</button><button id="rotate-token">Rotate device token</button><button class="danger" id="revoke-device">Revoke this device</button><button class="danger" id="forget-server">Forget server</button></div></section>
  <section class="section" id="server"><h2>Server</h2><div class="split"><label>Server URL<input readonly value="${escapeText(state.server.url)}"></label><label>TLS status<input readonly value="${state.server.url.startsWith('https:')?'HTTPS verified':'Loopback development'}"></label><label>Server instance ID<input readonly value="${state.server.instanceId}"></label><label>Compatibility<input readonly value="Server ${escapeText(state.server.serverVersion??'unknown')} · Protocol v1"></label></div></section>
  <section class="section" id="channels"><div class="row"><div class="grow"><h2>Channels</h2><span class="muted">Routing is one global mode; disabled choices prevent invalid combinations.</span></div><button id="create">Create channel</button></div><table class="channel-table"><thead><tr><th>Channel</th><th>Members</th><th>Send</th><th>Receive</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.channels.map((channel:any)=>{const joined=state.joined.find((value:any)=>value.id===channel.id);const route=state.routes.find((value:any)=>value.channelId===channel.id);const rule=rules.get(channel.id);const lifecycle=channel.member_count===1?`<button class="danger" data-delete="${channel.id}">Leave and delete channel</button>`:`<button data-leave="${channel.id}">Leave</button><button disabled title="Only the sole remaining member can delete. ${channel.member_count} devices are joined.">Delete</button>`;return`<tr><td><strong>${escapeText(channel.name)}</strong><br><span class="metric">${channel.id.slice(0,8)}</span></td><td>${channel.member_count}</td><td><input type="checkbox" data-route="send" data-id="${channel.id}" ${route?.sendEnabled?'checked':''} ${!joined||rule?.sendDisabled?'disabled':''} title="${escapeText(rule?.sendTooltip??'')}"></td><td><input type="checkbox" data-route="receive" data-id="${channel.id}" ${route?.receiveEnabled?'checked':''} ${!joined||rule?.receiveDisabled?'disabled':''} title="${escapeText(rule?.receiveTooltip??'')}"></td><td><span class="badge">${joined?'joined':'available'}</span></td><td>${joined?`<button data-members="${channel.id}">Members</button><button data-crypto="${channel.id}">Encryption</button><button data-copy-id="${channel.id}">Copy ID</button><button data-clear-channel="${channel.id}">Remove history</button>${lifecycle}`:`<button class="primary" data-join="${channel.id}">Join</button>`}</td></tr>`;}).join('')}</tbody></table></section>
  <section class="section" id="clipboard"><h2>Clipboard and files</h2>${clipboardPanel(currentText,hasSend)}${state.currentSource?`<p class="muted">Current remote item: ${escapeText(state.currentSource.device)} via ${escapeText(state.currentSource.channel)}</p>`:''}<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="split"><label>Send a file<input id="file-upload" type="file"></label><div><span class="muted">Files are encrypted in 4 MiB chunks and stored on the server until expiry.</span><div class="actions" style="margin-top:8px"><button class="primary" id="send-file" ${hasSend&&!state.pause.sending?'':'disabled'}>Upload and send</button><span class="metric" id="file-progress"></span></div></div></div><p class="metric">Auto-monitor: ${state.monitoring.active?'active':'inactive'} · poll ${state.monitoring.pollIntervalMs/1000}s · ${state.monitoring.recentRemoteSuppressions} recent echo suppression record(s)</p><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><h2>Pause controls</h2><div class="actions"><button data-pause="send">Pause sending</button><button data-pause="receive">Pause receiving</button><button data-pause="both">Pause both</button><button data-pause="1">Pause 1 minute</button><button data-pause="5">Pause 5 minutes</button><button class="primary" data-pause="resume">Resume</button></div><p class="muted">Sending: ${state.pause.sending?'paused':'active'} · Receiving: ${state.pause.receiving?'paused':'active'}</p></section>
  <section class="section" id="history"><div class="row"><h2 class="grow">Local history</h2><button class="danger" id="clear-history">Clear local history</button></div><div class="settings-grid"><label>Maximum entries<input id="max-entries" type="number" min="0" value="${state.historySettings.maxEntries}"></label><label>Maximum age (days)<input id="max-age" type="number" min="0" value="${state.historySettings.maxAgeDays}"></label><label>Maximum storage (MiB)<input id="max-bytes" type="number" min="0" value="${Math.round(state.historySettings.maxStorageBytes/1048576)}"></label></div><div class="row" style="margin:14px 0"><label class="check"><input id="history-enabled" type="checkbox" ${state.historySettings.historyEnabled?'checked':''}> Enabled</label><label class="check"><input id="store-sent" type="checkbox" ${state.historySettings.storeSentItems?'checked':''}> Store sent</label><label class="check"><input id="store-received" type="checkbox" ${state.historySettings.storeReceivedItems?'checked':''}> Store received</label><button id="save-history">Save retention</button></div><div class="settings-grid" style="margin-bottom:12px"><label>Channel<select id="filter-channel"><option value="">All channels</option>${[...new Set(state.history.map((entry:any)=>entry.channelNameSnapshot))].map((name)=>`<option>${escapeText(String(name))}</option>`).join('')}</select></label><label>Device<select id="filter-device"><option value="">All devices</option>${[...new Set(state.history.map((entry:any)=>entry.originDeviceNameSnapshot))].map((name)=>`<option>${escapeText(String(name))}</option>`).join('')}</select></label><label>Direction<select id="filter-direction"><option value="">Sent and received</option><option value="sent">Sent</option><option value="received">Received</option></select></label><label>Content<select id="filter-type"><option value="">Text, images, and files</option><option value="text/plain">Text</option><option value="image/png">PNG image</option><option value="application/vnd.clipmesh.file">File</option></select></label><label>From date<input id="filter-from" type="date"></label><label>Through date<input id="filter-through" type="date"></label></div><div id="history-list">${historyRows()}</div></section>
  <section class="section" id="security"><h2>Security</h2><div class="notice"><strong>Channel passwords cannot be recovered.</strong> Passwords never leave this extension. Use the generated high-entropy passphrase or a unique passphrase of at least six random words.</div><p>Channel keys are stored in Chrome local extension storage. They are isolated from webpages, but are not hardware-backed and may be exposed by a compromised OS account or browser profile.</p><label class="check" title="Planned for a future cryptographic migration"><input type="checkbox" disabled> Lock extension on browser restart (planned)</label><ul class="muted"><li>Clipboard content is authenticated with AES-256-GCM.</li><li>Passwords use bundled Argon2id WebAssembly at 64 MiB, three iterations, and four lanes.</li><li>Channel membership uses P-256 challenge signatures.</li><li>Incognito operation and remote executable code are disabled.</li></ul></section></div>`;
  document.querySelector('#history h2')?.insertAdjacentHTML('afterend',`<span class="metric">${state.historyUsage.entries} entries · ${(state.historyUsage.bytes/1048576).toFixed(2)} MiB</span>`);
  bind();
}

function bind():void{
  document.querySelectorAll<HTMLElement>('[data-scroll]').forEach((button)=>button.addEventListener('click',()=>document.querySelector(`#${button.dataset.scroll}`)?.scrollIntoView({behavior:'smooth'})));
  document.querySelector('#rename')?.addEventListener('click',()=>void act('rename-device',{name:value('#device-name')}));document.querySelector('#reconnect')?.addEventListener('click',()=>void act('reconnect'));document.querySelector('#rotate-token')?.addEventListener('click',()=>{if(confirm('Rotate the device token? Other active connections from this device will be disconnected.'))void act('rotate-token');});document.querySelector('#revoke-device')?.addEventListener('click',()=>void forget(true));document.querySelector('#forget-server')?.addEventListener('click',()=>void forget(false));document.querySelector('#create')?.addEventListener('click',()=>void createChannel());
  document.querySelectorAll<HTMLInputElement>('[data-route]').forEach((input)=>input.addEventListener('change',()=>void act('toggle-route',{channelId:input.dataset.id,side:input.dataset.route,enabled:input.checked})));
  document.querySelectorAll<HTMLElement>('[data-join]').forEach((button)=>button.addEventListener('click',()=>void joinChannel(button.dataset.join!)));
  document.querySelectorAll<HTMLElement>('[data-members]').forEach((button)=>button.addEventListener('click',()=>void showMembers(button.dataset.members!)));
  document.querySelectorAll<HTMLElement>('[data-crypto]').forEach((button)=>button.addEventListener('click',()=>void showEncryption(button.dataset.crypto!)));
  document.querySelectorAll<HTMLElement>('[data-copy-id]').forEach((button)=>button.addEventListener('click',()=>void navigator.clipboard.writeText(button.dataset.copyId!)));
  document.querySelectorAll<HTMLElement>('[data-clear-channel]').forEach((button)=>button.addEventListener('click',()=>{if(confirm('Delete local history associated with this channel?'))void act('clear-channel-history',{channelId:button.dataset.clearChannel});}));
  document.querySelectorAll<HTMLElement>('[data-leave]').forEach((button)=>button.addEventListener('click',()=>void leave(button.dataset.leave!,false)));
  document.querySelectorAll<HTMLElement>('[data-delete]').forEach((button)=>button.addEventListener('click',()=>void leave(button.dataset.delete!,true)));
  document.querySelector('#send-text')?.addEventListener('click',()=>void act('explicit-text',{text:value('#editor'),send:true}));document.querySelector('#copy-text')?.addEventListener('click',()=>void act('explicit-text',{text:value('#editor'),send:false}));document.querySelector('#send-image')?.addEventListener('click',()=>void act('explicit-image'));document.querySelector('#copy-current')?.addEventListener('click',()=>void act('copy-current'));document.querySelector('#remove-preview')?.addEventListener('click',()=>void act('remove-preview'));document.querySelector('#reload')?.addEventListener('click',()=>void act('reload-clipboard'));document.querySelector('#clear-editor')?.addEventListener('click',()=>{(document.querySelector('#editor') as HTMLTextAreaElement).value='';});
  document.querySelector('#send-file')?.addEventListener('click',()=>void sendFile());document.querySelector('#download-current')?.addEventListener('click',()=>void downloadCurrent());
  document.querySelector('#editor')?.addEventListener('input',(event)=>{const text=(event.target as HTMLTextAreaElement).value;document.querySelector('#editor-count')!.textContent=`${[...text].length} characters · ${new TextEncoder().encode(text).length} bytes`;});
  document.querySelectorAll<HTMLElement>('[data-pause]').forEach((button)=>button.addEventListener('click',()=>void pause(button.dataset.pause!)));
  document.querySelector('#save-history')?.addEventListener('click',()=>void saveHistory());document.querySelector('#clear-history')?.addEventListener('click',()=>{if(confirm('Delete every local history entry?'))void act('clear-history');});
  document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('#filter-channel,#filter-device,#filter-direction,#filter-type,#filter-from,#filter-through').forEach((select)=>select.addEventListener('change',filterHistory));
  document.querySelectorAll<HTMLElement>('[data-copy-history]').forEach((button)=>button.addEventListener('click',()=>void act('copy-history',{localId:button.dataset.copyHistory})));
  document.querySelectorAll<HTMLElement>('[data-download-history]').forEach((button)=>button.addEventListener('click',()=>void downloadHistory(button.dataset.downloadHistory!,button.dataset.channel!)));
  document.querySelectorAll<HTMLElement>('[data-resend]').forEach((button)=>button.addEventListener('click',()=>void act('resend-history',{localId:button.dataset.resend})));
  document.querySelectorAll<HTMLElement>('[data-delete-history]').forEach((button)=>button.addEventListener('click',()=>void act('delete-history',{localId:button.dataset.deleteHistory})));
  document.querySelectorAll<HTMLElement>('[data-preview]').forEach((button)=>button.addEventListener('click',()=>void previewHistory(button.dataset.preview!)));
}

async function createChannel():Promise<void>{const pending=showDialog('Create encrypted channel',`<label>Channel name<input name="name" maxlength="80" required></label><label>Encryption password<input name="password" type="password" minlength="12" required></label><label>Confirm password<input name="confirmation" type="password" minlength="12" required></label><div class="row"><meter id="password-strength" min="0" max="4" value="0" class="grow"></meter><button type="button" id="generate-passphrase">Generate strong passphrase</button></div><p class="notice">This password cannot be recovered. It never leaves this extension. Do not reuse an account password.</p>`);const password=document.querySelector<HTMLInputElement>('input[name=password]')!,confirmation=document.querySelector<HTMLInputElement>('input[name=confirmation]')!,meter=document.querySelector<HTMLMeterElement>('#password-strength')!;const update=()=>{meter.value=Math.min(4,password.value.length/8+(new Set(password.value).size>14?1:0));};password.addEventListener('input',update);document.querySelector('#generate-passphrase')?.addEventListener('click',()=>{const generated=`mesh-${crypto.randomUUID()}-${crypto.randomUUID()}`;password.value=generated;confirmation.value=generated;update();});const result=await pending;if(result)await act('create-channel',result);}
async function joinChannel(channelId:string):Promise<void>{const channel=state.channels.find((value:any)=>value.id===channelId);const result=await showDialog(`Join ${channel?.name??'channel'}`,`<label>Channel password<input name="password" type="password" required></label><p class="muted">The password is checked locally before a membership challenge is requested.</p>`);if(result)await act('join-channel',{channelId,...result});}
async function leave(channelId:string,deleting:boolean):Promise<void>{const verb=deleting?'Delete this channel for every member?':'Leave this channel?';if(!confirm(`${verb} You can also delete this device's local entries in the next prompt.`))return;const deleteHistory=confirm('Delete local history associated with this channel?');await act(deleting?'delete-channel':'leave-channel',{channelId,deleteHistory});}
async function showMembers(channelId:string):Promise<void>{try{const members=await command('channel-members',{channelId});await showDialog('Channel members',members.map((member:any)=>`<p><strong>${escapeText(member.name)}</strong><br><span class="metric">${member.id.slice(0,8)} · joined ${new Date(member.joined_at).toLocaleString()}</span></p>`).join(''));}catch(error){alert(message(error));}}
async function showEncryption(channelId:string):Promise<void>{const channel=state.joined.find((value:any)=>value.id===channelId);if(!channel)return;await showDialog('Encryption details',`<p>Envelope version: <strong>${channel.cryptoVersion}</strong></p><p>KDF: <strong>Argon2id</strong><br>${channel.kdf.memory_kib/1024} MiB · ${channel.kdf.iterations} iterations · ${channel.kdf.parallelism} lanes</p><p class="notice">The password and channel keys are never displayed.</p>`);}
async function forget(revoke:boolean):Promise<void>{if(!confirm(revoke?'Revoke this device on the server and remove its local channel keys?':'Forget this server and remove local channel keys from Chrome?'))return;const deleteHistory=confirm('Also delete all local encrypted history?');await act(revoke?'revoke-device':'forget-server',{deleteHistory});}
async function pause(kind:string):Promise<void>{const pause=kind==='resume'?{sending:false,receiving:false}:kind==='send'?{...state.pause,sending:true}:kind==='receive'?{...state.pause,receiving:true}:kind==='both'?{sending:true,receiving:true}: {sending:true,receiving:true,until:Date.now()+Number(kind)*60_000};await act('set-pause',{pause});}
async function saveHistory():Promise<void>{await act('set-history-settings',{settings:{historyEnabled:checked('#history-enabled'),maxEntries:number('#max-entries'),maxAgeDays:number('#max-age'),maxStorageBytes:number('#max-bytes')*1048576,storeSentItems:checked('#store-sent'),storeReceivedItems:checked('#store-received')}});}
function filterHistory():void{const channel=value('#filter-channel'),device=value('#filter-device'),direction=value('#filter-direction'),type=value('#filter-type'),from=value('#filter-from'),through=value('#filter-through');const fromTime=from?new Date(`${from}T00:00:00`).getTime():0,throughTime=through?new Date(`${through}T23:59:59.999`).getTime():Number.POSITIVE_INFINITY;document.querySelectorAll<HTMLElement>('[data-history-row]').forEach((row)=>{const time=Number(row.dataset.time);row.hidden=!!((channel&&row.dataset.channel!==channel)||(device&&row.dataset.device!==device)||(direction&&row.dataset.direction!==direction)||(type&&row.dataset.content!==type)||time<fromTime||time>throughTime);});}
async function previewHistory(localId:string):Promise<void>{try{const item=await command('preview-history',{localId});const body=item.type==='text/plain'?`<textarea readonly>${escapeText(decodeUtf8(fromBase64(item.bytes)))}</textarea>`:item.type==='image/png'?`<img alt="History preview" style="max-width:100%" src="data:image/png;base64,${item.bytes}"><p class="metric">${item.width} × ${item.height}</p>`:`<p><strong>${escapeText(item.filename)}</strong></p><p class="metric">${formatBytes(item.size)} · ${escapeText(item.mediaType)} · expires ${new Date(item.expiresAt*1000).toLocaleString()}</p>`;await showDialog('History item',body);}catch(error){alert(message(error));}}
async function sendFile():Promise<void>{const file=document.querySelector<HTMLInputElement>('#file-upload')?.files?.[0];if(!file){alert('Choose a file first');return;}const progress=document.querySelector('#file-progress')!;try{await uploadBrowserFile(file,(value)=>progress.textContent=`${value.phase} ${value.completed}/${value.total}${value.channel?` · ${value.channel}`:''}`);await load();}catch(error){alert(message(error));}}
async function downloadCurrent():Promise<void>{if(state.current?.type!==FILE_MANIFEST_CONTENT_TYPE||!state.currentSource?.channelId)return;try{await downloadBrowserFile(state.current,state.currentSource.channelId,fileProgress);}catch(error){alert(message(error));}}
async function downloadHistory(localId:string,channelId:string):Promise<void>{try{const item=await command('preview-history',{localId});if(item.type!==FILE_MANIFEST_CONTENT_TYPE)throw new Error('History entry is not a file');if(confirm(`Download ${item.filename}?`))await downloadBrowserFile(item,channelId,fileProgress);}catch(error){alert(message(error));}}
function fileProgress(value:{phase:string;completed:number;total:number;channel?:string}):void{const target=document.querySelector('#file-progress');if(target)target.textContent=`${value.phase} ${value.completed}/${value.total}${value.channel?` · ${value.channel}`:''}`;}
async function act(type:string,data:Record<string,unknown>={}):Promise<void>{try{await command(type,data);await load();}catch(error){alert(message(error));}}
async function command(type:string,data:Record<string,unknown>={}):Promise<any>{const response=await chrome.runtime.sendMessage({type,...data});if(!response?.ok)throw new Error(response?.error??'ClipMesh operation failed');return response.result;}
async function showDialog(title:string,html:string):Promise<Record<string,string>|undefined>{const dialog=document.querySelector<HTMLDialogElement>('#dialog')!,form=document.querySelector<HTMLFormElement>('#dialog-form')!;document.querySelector('#dialog-title')!.textContent=title;document.querySelector('#dialog-body')!.innerHTML=html;document.querySelector('#dialog-error')!.textContent='';dialog.showModal();return new Promise((resolve)=>{dialog.addEventListener('close',()=>{if(dialog.returnValue!=='default'){resolve(undefined);return;}const values:Record<string,string>={};new FormData(form).forEach((value,key)=>values[key]=String(value));resolve(values);},{once:true});});}
function value(selector:string):string{return(document.querySelector(selector) as HTMLInputElement|HTMLTextAreaElement).value;}function number(selector:string):number{return Number(value(selector));}function checked(selector:string):boolean{return(document.querySelector(selector) as HTMLInputElement).checked;}function message(error:unknown):string{return error instanceof Error?error.message:String(error);}function escapeText(value:string):string{return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function contentLabel(type:string):string{return type==='text/plain'?'Text':type==='image/png'?'PNG image':'File';}
function clipboardPanel(text:string,hasSend:boolean):string{if(state.current?.type==='image/png')return`<img alt="Current clipboard" style="max-width:100%;max-height:360px" src="data:image/png;base64,${state.current.bytes}"><p class="metric">${state.current.width} × ${state.current.height} · ${formatBytes(fromBase64(state.current.bytes).length)}</p><div class="actions"><button class="primary" id="send-image" ${hasSend?'':'disabled'}>Send image</button><button id="copy-current">Copy again</button><button id="remove-preview">Remove preview</button><button id="reload">Reload from clipboard</button></div>`;if(state.current?.type===FILE_MANIFEST_CONTENT_TYPE)return`<div class="file-card"><h3>${escapeText(state.current.filename)}</h3><p class="metric">${formatBytes(state.current.size)} · ${escapeText(state.current.mediaType)} · expires ${new Date(state.current.expiresAt*1000).toLocaleString()}</p><div class="actions"><button class="primary" id="download-current">Download file</button><button id="remove-preview">Remove preview</button><button id="reload">Reload from clipboard</button></div></div>`;return`<textarea id="editor">${escapeText(text)}</textarea><p class="metric" id="editor-count">${[...text].length} characters · ${new TextEncoder().encode(text).length} bytes</p><div class="actions"><button class="primary" id="send-text" ${hasSend?'':'disabled'}>Send and copy</button><button id="copy-text">Copy without sending</button><button id="reload">Reload from clipboard</button><button id="clear-editor">Clear editor</button></div>`;}
function historyRows():string{if(!state.history.length)return'<p class="muted">No history stored on this device.</p>';return state.history.map((entry:any)=>{const file=entry.contentType===FILE_MANIFEST_CONTENT_TYPE;const actions=file?`<button data-preview="${entry.localId}">Details</button><button class="primary" data-download-history="${entry.localId}" data-channel="${entry.channelId}">Download</button>`:`<button data-preview="${entry.localId}">Expand</button><button data-copy-history="${entry.localId}">Copy</button><button data-resend="${entry.localId}">Send again</button>`;return`<div class="history-row row" data-history-row data-channel="${escapeText(entry.channelNameSnapshot)}" data-device="${escapeText(entry.originDeviceNameSnapshot)}" data-direction="${entry.direction}" data-content="${entry.contentType}" data-time="${entry.storedAtLocal}"><div class="grow"><strong>${contentLabel(entry.contentType)}</strong> <span class="badge">${entry.direction}</span>${state.joined.some((channel:any)=>channel.id===entry.channelId)?'':' <span class="badge">locked</span>'}<br><span class="muted">${escapeText(entry.channelNameSnapshot)} · ${escapeText(entry.originDeviceNameSnapshot)} · ${new Date(entry.storedAtLocal).toLocaleString()}</span></div><span class="metric">${formatBytes(entry.byteSize)} · ${entry.deliveryStatus}</span><div class="actions">${actions}<button class="danger" data-delete-history="${entry.localId}">Delete</button></div></div>`;}).join('');}
