import { checkboxRules } from '../channels/routing';
import { installFocusedClipboardWriter } from '../clipboard/focused';
import { decodeUtf8, fromBase64 } from '../crypto/encoding';
import { downloadBrowserFile, formatBytes, uploadBrowserFile } from '../files/transfer';
import { FILE_MANIFEST_CONTENT_TYPE, type RouteSelection } from '../shared/types';

const root=document.querySelector<HTMLElement>('#app')!;
let state:any;

installFocusedClipboardWriter();

void load();
async function load():Promise<void>{try{state=await command('get-state');render();}catch(error){root.innerHTML=`<p class="form-error">${escapeText(errorMessage(error))}</p>`;}}

function render():void{
  if(!state.configured){renderPairing();return;}
  const rules=checkboxRules(state.routes as RouteSelection[],(id)=>state.joined.find((channel:any)=>channel.id===id)?.name??id);const text=state.current?.type==='text/plain'?decodeUtf8(fromBase64(state.current.bytes)):'';const hasSend=state.routes.some((route:any)=>route.sendEnabled);
  root.innerHTML=`<div class="popup-head"><div><div class="brand">ClipMesh</div><span class="muted">${escapeText(state.server.deviceName)} · server ${escapeText(state.server.instanceId.slice(0,8))}</span></div><span class="status ${state.connection==='connected'?'connected':''}">${escapeText(state.connection)}</span></div>${state.clipboardError?`<p class="notice">${escapeText(state.clipboardError)}</p>`:''}${state.operationError?`<p class="notice">Latest warning: ${escapeText(state.operationError)}</p>`:''}${state.pending?`<p class="notice">Newest ${contentLabel(state.pending.contentType).toLowerCase()} item pending for ${state.pending.targetChannelIds.length} channel(s). A newer local item will replace it.</p>`:''}
  <section class="clipboard-card"><div class="row"><span class="eyebrow grow">Current item</span><span class="badge">${escapeText(state.mode)}</span></div>${currentPanel(text,hasSend)}${state.currentSource?`<p class="muted">From ${escapeText(state.currentSource.device)} via ${escapeText(state.currentSource.channel)}</p>`:''}<hr style="border:0;border-top:1px solid var(--line);margin:14px 0"><label>Send a file<input id="file-upload" type="file"></label><div class="actions" style="margin-top:8px"><button class="primary" id="send-file" ${hasSend&&!state.pause.sending?'':'disabled'}>Upload and send</button><span class="metric" id="file-progress"></span></div></section>
  <section class="section"><div class="row"><h2 class="grow">Channels</h2><span class="badge">${state.routes.length}</span></div>${state.joined.length?state.joined.map((channel:any)=>{const route=state.routes.find((value:any)=>value.channelId===channel.id);const rule=rules.get(channel.id);return`<div class="channel-mini"><span>${escapeText(channel.name)}</span><label class="check" title="${escapeText(rule?.sendTooltip??'')}"><input data-channel="${channel.id}" data-side="send" type="checkbox" ${route?.sendEnabled?'checked':''} ${rule?.sendDisabled?'disabled':''}> Send</label><label class="check" title="${escapeText(rule?.receiveTooltip??'')}"><input data-channel="${channel.id}" data-side="receive" type="checkbox" ${route?.receiveEnabled?'checked':''} ${rule?.receiveDisabled?'disabled':''}> Receive</label></div>`;}).join(''):'<p class="muted">Join a channel from the full page.</p>'}</section>
  <section class="section"><h2>Recent local history</h2>${state.history.length?state.history.slice(0,5).map((entry:any)=>`<div class="history-row"><div>${contentLabel(entry.contentType)} <span class="badge">${entry.direction}</span></div><div class="muted">${escapeText(entry.channelNameSnapshot)} · ${new Date(entry.storedAtLocal).toLocaleString()}</div></div>`).join(''):'<p class="muted">No local entries yet.</p>'}</section><button class="footer-link" id="options">Open full ClipMesh</button>`;
  if(!state.routes.some((route:any)=>route.sendEnabled)){for(const id of ['send','send-image']){const button=document.querySelector<HTMLButtonElement>(`#${id}`);if(button){button.disabled=true;button.title='Select at least one Send channel.';}}}
  bindConfigured();
}

function renderPairing():void{root.innerHTML=`<div class="popup-head"><div class="brand">ClipMesh</div><span class="badge">Pairing required</span></div><section class="pair-card"><h2>Connect this browser</h2><p class="muted">Use the five-minute code shown by your ClipMesh server.</p><label>Server URL<input id="server" type="url" placeholder="https://clipmesh.example.com"></label><label>Pairing code<input id="code" autocomplete="one-time-code" placeholder="ABCD-EFGH"></label><label>Device name<input id="name" maxlength="80" value="${escapeText(defaultDeviceName())}"></label><p id="error" class="form-error"></p><button class="primary" id="pair">Pair device</button></section>`;void prefillServer();document.querySelector('#pair')?.addEventListener('click',()=>void pair());}

function bindConfigured():void{
  document.querySelector('#options')?.addEventListener('click',()=>void chrome.runtime.openOptionsPage());document.querySelector('#reload')?.addEventListener('click',()=>void act('reload-clipboard'));
  document.querySelector('#send')?.addEventListener('click',()=>void sendText(true));document.querySelector('#copy')?.addEventListener('click',()=>void sendText(false));
  document.querySelector('#send-image')?.addEventListener('click',()=>void act('explicit-image'));
  document.querySelector('#copy-current')?.addEventListener('click',()=>void act('copy-current'));document.querySelector('#remove-preview')?.addEventListener('click',()=>void act('remove-preview'));
  document.querySelector('#send-file')?.addEventListener('click',()=>void sendFile());document.querySelector('#download-current')?.addEventListener('click',()=>void downloadCurrent());
  document.querySelector('#editor')?.addEventListener('input',(event)=>{const text=(event.target as HTMLTextAreaElement).value;document.querySelector('#count')!.textContent=`${[...text].length} characters · ${new TextEncoder().encode(text).length} bytes`;});
  document.querySelectorAll<HTMLInputElement>('input[data-channel]').forEach((input)=>input.addEventListener('change',()=>void act('toggle-route',{channelId:input.dataset.channel,side:input.dataset.side,enabled:input.checked})));
}
async function pair():Promise<void>{const serverUrl=value('#server'),pairingCode=value('#code'),deviceName=value('#name');const error=document.querySelector('#error')!;try{const allowed=await chrome.permissions.request({origins:[permissionOrigin(serverUrl)]});if(!allowed)throw new Error('Server access was not granted');await command('pair',{input:{serverUrl,pairingCode,deviceName}});await load();}catch(reason){error.textContent=errorMessage(reason);}}
async function prefillServer():Promise<void>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab?.url){const url=new URL(tab.url);if(url.protocol==='https:'||url.hostname==='localhost'||url.hostname==='127.0.0.1')(document.querySelector('#server') as HTMLInputElement).value=url.origin;}}
async function sendText(send:boolean):Promise<void>{await act('explicit-text',{text:value('#editor'),send});}
async function sendFile():Promise<void>{const file=document.querySelector<HTMLInputElement>('#file-upload')?.files?.[0];if(!file){alert('Choose a file first');return;}const progress=document.querySelector('#file-progress')!;try{await uploadBrowserFile(file,(value)=>progress.textContent=`${value.phase} ${value.completed}/${value.total}${value.channel?` · ${value.channel}`:''}`);await load();}catch(error){alert(errorMessage(error));}}
async function downloadCurrent():Promise<void>{if(state.current?.type!==FILE_MANIFEST_CONTENT_TYPE||!state.currentSource?.channelId)return;try{await downloadBrowserFile(state.current,state.currentSource.channelId,(value)=>{const progress=document.querySelector('#file-progress');if(progress)progress.textContent=`${value.phase} ${value.completed}/${value.total}`;});}catch(error){alert(errorMessage(error));}}
async function act(type:string,data:Record<string,unknown>={}):Promise<void>{try{await command(type,data);await load();}catch(error){globalThis.alert(errorMessage(error));}}
async function command(type:string,data:Record<string,unknown>={}):Promise<any>{const response=await chrome.runtime.sendMessage({type,...data});if(!response?.ok)throw new Error(response?.error??'ClipMesh operation failed');return response.result;}
function value(selector:string):string{return(document.querySelector(selector) as HTMLInputElement|HTMLTextAreaElement).value;}
function defaultDeviceName():string{return navigator.platform||'Chrome desktop';}
function permissionOrigin(input:string):string{const url=new URL(input);const loopback=['localhost','127.0.0.1','[::1]'].includes(url.hostname);if(url.protocol!=='https:'&&!(loopback&&url.protocol==='http:'))throw new Error('HTTPS is required outside loopback development');return`${url.origin}/*`;}
function errorMessage(error:unknown):string{return error instanceof Error?error.message:String(error);}
function escapeText(value:string):string{return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function contentLabel(type:string):string{return type==='text/plain'?'Text':type==='image/png'?'PNG image':'File';}
function currentPanel(text:string,hasSend:boolean):string{if(state.current?.type==='image/png')return`<img alt="Clipboard preview" style="max-width:100%;max-height:180px;margin:10px 0" src="data:image/png;base64,${state.current.bytes}"><div class="metric">${state.current.width} × ${state.current.height}</div><div class="actions" style="margin-top:10px"><button class="primary" id="send-image" ${hasSend?'':'disabled'}>Send image</button><button id="copy-current">Copy again</button><button id="remove-preview">Remove preview</button><button id="reload">Reload</button></div>`;if(state.current?.type===FILE_MANIFEST_CONTENT_TYPE)return`<h2 style="margin:12px 0 4px">${escapeText(state.current.filename)}</h2><div class="metric">${formatBytes(state.current.size)} · expires ${new Date(state.current.expiresAt*1000).toLocaleString()}</div><div class="actions" style="margin-top:10px"><button class="primary" id="download-current">Download</button><button id="remove-preview">Remove preview</button><button id="reload">Reload</button></div>`;return`<textarea id="editor" placeholder="Clipboard text">${escapeText(text)}</textarea><div class="metric" id="count">${[...text].length} characters · ${new TextEncoder().encode(text).length} bytes</div><div class="actions" style="margin-top:10px"><button class="primary" id="send" ${hasSend?'':'disabled'}>Send and copy</button><button id="copy">Copy only</button><button id="reload">Reload</button></div>`;}
